spring.application.name=ex25-branch
server.port=8020

#maria DB 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=1234

#mybatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.nyg.mybatis.domain
mybatis.configuration.map-underscore-to-camel-case=true



logging.level.com.skc.mybatis.mapper=DEBUG


server.servlet.encoding.charset=UTF-8
�server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true


# 로그 파일 자동 생성 경로 및 이름 지정
logging.file.name=logs/app.log
# 또는 디렉토리만 지정할 수도 있음
# logging.file.path=logs
# 로그 레벨 설정
logging.level.root=info
logging.level.com.nyg.service=debug
logging.level.com.nyg=debug